#timestamp:20250402125100899040705
services:
  ultra-coins-blog:
    image: ghcr.io/ultra-coins/ultra-coins-blog/blog
    container_name: ultra-coins-blog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
