name: deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: blog

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check Articles
        run: nix develop --command bash -c "zola check"
  container:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Current Time (Tag Name)
        id: tag
        run: echo "time=$(date +%Y%m%d%H%M%S%9N)" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.time }}
      - name: Convert base_url for gh-pages
        run: sed -i '3 s/ghcr.io\/ultra-coins\/ultra-coins-blog\/blog/ghcr.io\/ultra-coins\/ultra-coins-blog\/blog:${{ steps.tag.outputs.time }}/g' prod.compose.yaml
      - name: Show prod.compose.yaml
        run: cat prod.compose.yaml
